### ISSUE TITLE
Tool workflow clarification?

### ISSUE THREAD

**Issue by davnguye** [marcellusparley/ac-emblem-tool#3]
Hey, thanks for doing this and sharing it with the community! I have a really stupid question for the tool binary as I am not too familiar with C++. What is the expected workflow for the tool? I am running the latest release and am dropping both the emblem save file and emblem png into the CLI, but the CLI closes upon pressing enter with no changes made to the save file. Am I missing something? Thanks again :)

**Comment by mparley** [comment]
Huh that's kinda odd. Does it give you any error or does it close immediately? Does it create a .backup save file or anything in the folder? 

The workflow if you are using CLI should just be
`.\acet.exe SAVE image.png`
The other method is selecting both save and image and dragging them onto the exe in windows explorer - though don't know if something similar works on linux since I only tested the cli there.

**Comment by davnguye** [comment]
Hey, thanks for getting back to me and sorry for the delay!
I think I misspoke when I mentioned the CLI. I am using the 1.0.2 .exe. The window closes immediately after pressing the enter key and no .backup is created either. The steps I did are as follows:
1. Open acet.exe
![image](https://github.com/mparley/ac-emblem-tool/assets/54002653/540b5d87-2788-4ff1-a5c9-f0ac6cd2887d)
2. Drop both save file and image into the window
![image](https://github.com/mparley/ac-emblem-tool/assets/54002653/ded95864-c056-47b6-94bd-29bc10c03596)
3. Window closes after pressing enter

**Comment by mparley** [comment]
Oh I see what's going on. You are opening the program without passing in anything so it's displaying the help message - I probably should change the message to 'press a key to close' since its just there to keep the window from closing. 

You have to drag and drop both files (at the same time) onto the acet.exe icon/program in windows explorer. You don't have to click on or open the exe itself.
![out](https://github.com/mparley/ac-emblem-tool/assets/35544859/7b88140f-68af-4c47-a26c-4a426cff4032)
Also its a good sanity check to drag the modified SAVE file onto the tool to see if it extracts the same image you put in

Also you may or may not run into problems with .psu saves. I tested them out way back when and it did work with .psu but I can't guarantee it will work now (though I know for certain it won't work with last raven) and you might have to use something like mymc to convert it to/from the raw save and back into whatever memory card you got it from.

**Comment by davnguye** [comment]
Awesome! I got it working in AC2 following the steps you provided. I appreciate the help, thanks!
